#12 filmorate. add-mark
zxc17/java-filmorate pull request #26
Opened 2022-08-26 11:15 UTC by zxc17

2022-08-26 19:42 UTC, svstudy-yandex commented
Как-то многовато тестов упало. Ты их разбирал?

2022-08-26 20:23 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>              f.setGenres(genreStorage.getNames(f.getGenres()));
Я правильно понял, что цель этого вызова - обновить названия жанров на случай если они обновились? 
Название метода getNames немного сбивает - оно все-таки возвращает жанры. Но это nice to have
Аналогично с режиссерами ниже

2022-08-26 20:23 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (rate == null || rate <= 0 || rate > 10)
Здесь и в конце файла есть логика, что рейтинг должен быть от 1 до 10 - я бы это вынес в одно место (метод)

2022-08-26 20:23 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public Review changeUseful(Long id, Long userId, boolean isAdd, boolean isLike) {
Useful - это прилагательное. Usefulness будет логичнее

2022-08-26 20:23 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "order by avg(RATE) desc ";
лучше явно указывать имя таблицы/алиас у колонки

2022-08-26 20:23 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "select FILMS.*, MPA_NAME " +
Лучше придерживаться одного стиля в программе. Сейчас где-то ключевые слова в SQL написаны маленькими, где-то большими

2022-08-26 20:45 UTC, svstudy-yandex commented
В целом всё ок! Единственное на будущее - лучше разделять рефакторинг и новый функционал на разные ПРы, чтобы было проще смотреть

2022-08-26 20:45 UTC, svstudy-yandex requested changes

2022-08-26 20:45 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
>                  "GROUP BY FILMS.film_id " +
Раз мы убрали единственный left join с лайками, нужен ли нам теперь group by?

2022-08-26 20:45 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dbStorageUtil.java
> +    static {
Есть встроенные ср-ва, чтобы читать эти свойства
https://stackoverflow.com/questions/30528255/how-to-access-a-value-defined-in-the-application-properties-file-in-spring-boot

Понятное дело придется сделать класс не статичным, а компонентом, в который можно инжектить зависимости

2022-08-27 02:52 UTC, zxc17 commented
> 

Как ты ответил в слаке - поскольку тестов под эту ветку нет, эндпоинты придумывать самим. Я добавление оценки вставил в обязательный параметр запроса. 
```
    @PutMapping("/films/{id}/like/{userId}")
    public void putLike(@PathVariable long id,
                        @PathVariable long userId,
                        @RequestParam() Integer rate) {
        log.info("Начато выполнение \"Добавить лайк фильму\".");
        filmService.putLike(id, userId, rate);
    }

```
Поэтому старые тесты падают. Скорректированные лежат в папке postman в моем репозитории.

2022-08-27 03:14 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>              f.setGenres(genreStorage.getNames(f.getGenres()));
Примерно так. В теле запроса (из тестов) названия жанров/рейтингов отсутствуют. Я решил, что будет лучше, если в ответе будут полные данные, а не только ID. Оттуда и взялось getNames - добавить имена жанров. Впрочем, это устарело. Всю эту конструкцию лучше заменить на `loadDataIntoFilm(f);`, которая используется и для других методов. Осталось, поскольку делал этот метод в самом начале, подзабылось.

2022-08-27 03:30 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (rate == null || rate <= 0 || rate > 10)
Исправил.

2022-08-27 03:31 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public Review changeUseful(Long id, Long userId, boolean isAdd, boolean isLike) {
Исправил

2022-08-27 03:42 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "order by avg(RATE) desc ";
Исправил

2022-08-27 03:48 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "select FILMS.*, MPA_NAME " +
Абсолютно согласен.
Но... Сразу не согласовали, а когда начали присылать ПР на командные ревью, то побоялся затянуть процесс, не стал требовать переписать. Частично исправил, когда работал над этой частью, но это довольно много времени занимает, больше уделял внимания тестированию и бизнес-логике.

2022-08-27 04:03 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
>                  "GROUP BY FILMS.film_id " +
Не нужен. Просмотрел. Исправлено.

2022-08-27 04:03 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dbStorageUtil.java
> +    static {
буду знать.

2022-08-27 04:11 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "select FILMS.*, MPA_NAME " +
Сейчас пробежался, всё, что заметил, поправил.

2022-08-27 04:12 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dbStorageUtil.java
> +    static {
Пока не разбирался, на досуге посмотрю, спасибо за инфу.

2022-08-27 04:19 UTC, zxc17 commented
> В целом всё ок! Единственное на будущее - лучше разделять рефакторинг и новый функционал на разные ПРы, чтобы было проще смотреть

Да, сразу не сообразил сделать отдельную ветку после реализации нового функционала, а потом уже всё перемешалось.

2022-08-27 11:15 UTC, zxc17 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dbStorageUtil.java
> +    static {
Сделано.

2022-08-27 15:00 UTC, svstudy-yandex approved these changes
Кажется все ок - хорошая работа)

2022-08-27 15:00 UTC, svstudy-yandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "group by FILMS.FILM_ID " +
C F.FILM_ID было все нормально) Я имел ввиду, что вместо RATE - F.RATE. Если для таблицы указан алиас, то лучше его и использовать

2022-08-27 15:13 UTC, merged